%matplotlib inline

In [4]:
from __future__ import division
from numpy.random import randn
import numpy as np 
np.set_printoptions(precision = 4,suppress = True)

In [5]:
data = randn(2,3)

In [6]:
data

array([[ 0.1756,  0.8761, -0.774 ],
       [-2.2796, -0.4582, -0.3522]])

In [7]:
data *10

array([[  1.7559,   8.7613,  -7.7398],
       [-22.7958,  -4.582 ,  -3.5216]])

In [8]:
data + data

array([[ 0.3512,  1.7523, -1.548 ],
       [-4.5592, -0.9164, -0.7043]])

In [9]:
data.shape()

TypeError: 'tuple' object is not callable

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [6,7.5,8,0,1]

In [13]:
arr1 = np.array(data1)

In [20]:
arr1


array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [22]:
arr1.shape

(5,)

In [15]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [16]:
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 4)

In [24]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [25]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [26]:
np.empty((2,3,2))

array([[[ -2.6816e+154,   4.3324e-311],
        [  2.9644e-323,   0.0000e+000],
        [  0.0000e+000,   0.0000e+000]],

       [[ -2.6816e+154,  -2.6816e+154],
        [  1.2686e-076,   1.4007e-076],
        [  3.9991e+252,   9.0372e-309]]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [30]:
arr1 = np.array([1,2,3],dtype = np.float64)

In [31]:
arr1

array([ 1.,  2.,  3.])

In [32]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [33]:
float_arr = arr.astype(float)

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7,-1.2,-2.6,0.5])

In [36]:
arr

array([ 3.7, -1.2, -2.6,  0.5])

In [38]:
arr.astype(np.int32)

array([ 3, -1, -2,  0], dtype=int32)

In [40]:
numeric_string = np.array(['12','4','6'],dtype = np.string_)

In [42]:
numeric_string.astype(np.int32)

array([12,  4,  6], dtype=int32)

In [43]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [44]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [45]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [46]:
arr -arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [47]:
1/arr

array([[ 1.    ,  0.5   ,  0.3333],
       [ 0.25  ,  0.2   ,  0.1667]])

In [48]:
 arr*0.5

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ]])

In [49]:
arr = np.arange(10)

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[5]

5

In [52]:
arr[5:8]

array([5, 6, 7])

In [64]:
arr[5:8] = 12

In [65]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [66]:
arr_slice = arr[5:8]

In [67]:
arr_slice[1] = 12345

In [68]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [69]:
arr_slice[:]

array([   12, 12345,    12])

In [70]:
arr_slice[:] =64

In [71]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [72]:
arr2d =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [73]:
arr2d[2]

array([7, 8, 9])

In [74]:
arr2d[1][2]

6

In [76]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [77]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [79]:
old_values = arr3d[0].copy()

In [81]:
arr3d[0] =42

In [82]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
arr3d[0] = old_values

In [84]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [85]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [86]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [89]:
arr2d[1,:2]

array([4, 5])

In [90]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [92]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data =randn(7,4)
names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [93]:
data

array([[-0.1121, -0.2883, -0.6738, -1.1307],
       [ 1.0237,  0.5383, -1.275 ,  1.1065],
       [ 0.9525,  0.0089,  0.1505, -0.0248],
       [ 0.1482, -0.0922,  0.411 , -0.9912],
       [ 0.1414, -1.023 ,  0.9089,  0.1235],
       [ 0.7238, -1.5064, -0.9349,  0.3074],
       [-0.9002,  0.8056,  1.1171,  0.0732]])

In [94]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [96]:
data[names =='Bob',2:]

array([[-0.6738, -1.1307],
       [ 0.411 , -0.9912]])

In [97]:
data[-(names == 'Bob')]

/Users/hikari/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  if __name__ == '__main__':


array([[ 1.0237,  0.5383, -1.275 ,  1.1065],
       [ 0.9525,  0.0089,  0.1505, -0.0248],
       [ 0.1414, -1.023 ,  0.9089,  0.1235],
       [ 0.7238, -1.5064, -0.9349,  0.3074],
       [-0.9002,  0.8056,  1.1171,  0.0732]])

In [99]:
mask = (names =='Bob')|(names=='Will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [100]:
data[mask]

array([[-0.1121, -0.2883, -0.6738, -1.1307],
       [ 0.9525,  0.0089,  0.1505, -0.0248],
       [ 0.1482, -0.0922,  0.411 , -0.9912],
       [ 0.1414, -1.023 ,  0.9089,  0.1235]])

In [101]:
data[data<0]

array([-0.1121, -0.2883, -0.6738, -1.1307, -1.275 , -0.0248, -0.0922,
       -0.9912, -1.023 , -1.5064, -0.9349, -0.9002])

In [102]:
data[names == 'Joe']=8

In [103]:
data

array([[-0.1121, -0.2883, -0.6738, -1.1307],
       [ 8.    ,  8.    ,  8.    ,  8.    ],
       [ 0.9525,  0.0089,  0.1505, -0.0248],
       [ 0.1482, -0.0922,  0.411 , -0.9912],
       [ 0.1414, -1.023 ,  0.9089,  0.1235],
       [ 8.    ,  8.    ,  8.    ,  8.    ],
       [ 8.    ,  8.    ,  8.    ,  8.    ]])

In [104]:
arr = np.empty((8,4))

In [105]:
for i in range(8):
    arr[i]= i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [106]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [108]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [110]:
arr = np.arange(32).reshape(8,4)

In [111]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [112]:
arr[[1,5,7,2],[0,3,1,1,]]

array([ 4, 23, 29,  9])

In [113]:
arr = np.arange(15).reshape(3,5)

In [114]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [115]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [116]:
arr = np.random.randn(6,3)

In [117]:
np.dot(arr.T,arr)

array([[ 7.5067, -1.9313, -3.6938],
       [-1.9313,  6.0486,  0.8439],
       [-3.6938,  0.8439,  3.8682]])

In [ ]:
arr.