from pandas import Series, DataFrame

In [3]:
import pandas as pd 
obj = Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4,7,-5,3],index = ['d','b','c','a'])

In [8]:
obj2

d    4
b    7
c   -5
a    3
dtype: int64

In [9]:
obj2['a']

3

In [10]:
obj2['d']= 6
obj2

d    6
b    7
c   -5
a    3
dtype: int64

In [11]:
obj2[obj2>0]

d    6
b    7
a    3
dtype: int64

In [12]:
obj2*2

d    12
b    14
c   -10
a     6
dtype: int64

In [13]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
c       0.006738
a      20.085537
dtype: float64

In [14]:
'b' in obj2

True

In [15]:
'e'in obj2

False

In [16]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)

In [17]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [18]:
states = ['California','Ohio','Oregon','Texas']
obj4 = Series(sdata,index=states)

In [19]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [20]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [22]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [24]:
obj4.name='population'

In [25]:
obj4.index.name='state'

In [26]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [27]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [28]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [29]:
DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [30]:
frame2 = DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five'])

In [31]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [32]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [33]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [34]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [35]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [36]:
frame2['debt']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
Name: debt, dtype: object

In [37]:
frame2['debt'] = 16.5

In [38]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [39]:
frame2['debt']=np.arange(5.)

In [40]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [41]:
val = Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [42]:
frame2['debt'] = val

In [43]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [44]:
frame2['eastern'] = frame2.state =='Ohio'

In [45]:
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [46]:
del frame2['eastern']

In [47]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [49]:
frame3 = DataFrame(pop)

In [50]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [51]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [52]:
DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [53]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [54]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [55]:
frame3.index.name = 'year';frame3.columns.name='state'

In [56]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [57]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [58]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [59]:
obj = Series(range(3),index = ['a','b','c'])
index = obj.index

In [60]:
index

Index(['a', 'b', 'c'], dtype='object')

In [61]:
index[1:]

Index(['b', 'c'], dtype='object')

In [62]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [ ]:
index = pd.Index(np.arange(3))

In [63]:
obj2 = Series([1.5,-2.5,0],index =index)

In [64]:
obj2.index is index

True

In [65]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [66]:
'Ohio' in frame3.columns

True

In [67]:
2003 in frame3.index

False

In [68]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [69]:
obj2 = obj.reindex(['a','b','c','d','e'],fill_value=0)

In [70]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [71]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [72]:
frame = DataFrame(np.arange(9).reshape((3,3)),index=['a','b','c'],columns=['Ohio', 'Texas', 'California'])

In [73]:
frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [74]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [75]:
states = ['Texas','Utah','California']

In [76]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

In [77]:
frame.reindex(index=['a','b','c','d'],method ='ffill',columns = states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8
d      7   NaN           8

In [78]:
frame.ix[['a','b','c','d'],states]

Texas  Utah  California
a    1.0   NaN         2.0
b    4.0   NaN         5.0
c    7.0   NaN         8.0
d    NaN   NaN         NaN

In [79]:
obj = Series(np.arange(5.),index =['a','b','c','d','e'])

In [80]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [81]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [82]:
data = DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns =['one','two','three','four'])

In [83]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [84]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [85]:
data.drop(['two','four'],axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [86]:
obj  = Series(np.arange(4.),index=['a','b','c','d'])

In [87]:
obj['b']

1.0

In [88]:
obj[1]

1.0

In [89]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [90]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [91]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [92]:
data = DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns =['one','two','three','four'])

In [93]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [94]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [95]:
data['three']

Ohio         2
Colorado     6
Utah        10
New York    14
Name: three, dtype: int64

In [96]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [97]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [98]:
data[data<5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [99]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [100]:
data.ix['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [101]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [102]:
data.ix[:'Utah','two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

In [103]:


s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [104]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [105]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [106]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [107]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])


In [108]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [109]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [110]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [111]:
df1 = DataFrame( np.arange(12.).reshape((3,4)),columns=list('abcd'))

In [112]:
df2 = DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))

In [113]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [114]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [115]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [116]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [117]:
df1.reindex(columns= df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [118]:
arr = np.arange(12.).reshape((3,4))

In [119]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [120]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [121]:
arr -arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [122]:
frame = DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [123]:
series = frame.ix[0]

In [124]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [125]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [126]:
frame -series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [127]:
series2 = Series(range(3),index=['b','d','e'])

In [128]:
frame +series2

b     d     e
Utah    0.0   2.0   4.0
Ohio    3.0   5.0   7.0
Texas   6.0   8.0  10.0
Oregon  9.0  11.0  13.0

In [129]:
series3 = frame['d']

In [130]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [131]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [132]:
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [133]:
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [134]:
frame

b         d         e
Utah    0.042042 -1.547336  0.669324
Ohio    0.606744  0.286051  1.603943
Texas  -1.029695 -0.796637 -1.539316
Oregon -0.849001  1.040658  0.311316

In [135]:
np.abs(frame)

b         d         e
Utah    0.042042  1.547336  0.669324
Ohio    0.606744  0.286051  1.603943
Texas   1.029695  0.796637  1.539316
Oregon  0.849001  1.040658  0.311316

In [136]:
f = lambda x: x.max() -x.min()

In [137]:
frame.apply(f)

b    1.636439
d    2.587994
e    3.143258
dtype: float64

In [138]:
frame.apply(f,axis=1)

Utah      2.216660
Ohio      1.317892
Texas     0.742678
Oregon    1.889658
dtype: float64

In [139]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])

In [140]:
frame.apply(f)

b         d         e
min -1.029695 -1.547336 -1.539316
max  0.606744  1.040658  1.603943

In [141]:
format = lambda x: '%.2f' % x

In [142]:
frame.applymap(format)

b      d      e
Utah     0.04  -1.55   0.67
Ohio     0.61   0.29   1.60
Texas   -1.03  -0.80  -1.54
Oregon  -0.85   1.04   0.31

In [143]:
frame['e'].map(format)

Utah       0.67
Ohio       1.60
Texas     -1.54
Oregon     0.31
Name: e, dtype: object

In [144]:
obj = Series(range(4),index=['d','b','a','c'])

In [145]:
obj.sort_index()

a    2
b    1
c    3
d    0
dtype: int64

In [146]:
frame = DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['a','b','c','d'])

In [147]:
frame.sort_index()

a  b  c  d
one    4  5  6  7
three  0  1  2  3

In [148]:
frame.sort_index(axis=1)

a  b  c  d
three  0  1  2  3
one    4  5  6  7

In [149]:
obj =Series([4,7,-3,2])

In [150]:
obj.order()

/Users/hikari/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: order is deprecated, use sort_values(...)
  if __name__ == '__main__':


2   -3
3    2
0    4
1    7
dtype: int64

In [151]:
obj= Series([4,np.nan,7,np.nan,-3,2])

In [152]:
obj.order()

/Users/hikari/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: order is deprecated, use sort_values(...)
  if __name__ == '__main__':


4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [153]:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [154]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [155]:
frame.sort_index(by='b')

/Users/hikari/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':


a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [156]:
obj =Series([7,-5,7,4,3,3,2,0])

In [157]:
obj.rank()

0    7.5
1    1.0
2    7.5
3    6.0
4    4.5
5    4.5
6    3.0
7    2.0
dtype: float64

In [158]:
obj.rank(method='first')

0    7.0
1    1.0
2    8.0
3    6.0
4    4.0
5    5.0
6    3.0
7    2.0
dtype: float64

In [159]:
obj.rank(ascending=False,method='max')

0    2.0
1    8.0
2    2.0
3    3.0
4    5.0
5    5.0
6    6.0
7    7.0
dtype: float64

In [160]:
frame = DataFrame({'b':[4.3,7,-3,3],'a':[0,1,0,1],'c':[-2.5,3,8,-2]})

In [161]:
frame

a    b    c
0  0  4.3 -2.5
1  1  7.0  3.0
2  0 -3.0  8.0
3  1  3.0 -2.0

In [162]:
frame.rank()

a    b    c
0  1.5  3.0  1.0
1  3.5  4.0  3.0
2  1.5  1.0  4.0
3  3.5  2.0  2.0

In [163]:
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

In [164]:
obj = Series(range(5),index=['a','a','b','b','c'])

In [165]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [166]:
obj.index.is_unique

False

In [167]:
obj['a']

a    0
a    1
dtype: int64

In [168]:
obj['c']

4

In [169]:
df = DataFrame(np.random.randn(4,3),index=['a','a','b','b'])

In [170]:
df

0         1         2
a  0.980186 -0.228070  0.114647
a -0.298439  0.247632  0.209197
b -0.973485  0.141022  0.923210
b  0.869816  0.271447 -0.998360

In [171]:
df.ix[b]

NameError: name 'b' is not defined

In [172]:
df  = DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index = ['a','b','c','d'],columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [173]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [174]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [175]:
df.idxmax()

one    b
two    d
dtype: object

In [176]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [177]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [178]:
obj = Series(['c','a','d','a','a','b','b','c','c'])


In [179]:
uniques = obj.unique()

In [180]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [181]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [182]:
pd.value_counts(obj.values,sort= False)

d    1
b    2
a    3
c    3
dtype: int64

In [183]:
mask=obj.isin(['b','c'])

In [184]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [185]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [186]:
data  = DataFrame({'Qu1':[1,3,4,3,4],'Qu2':[2,3,1,2,3],'Qu3':[1,5,2,4,4]})

In [187]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [188]:
result = data.apply(pd.value_counts).fillna(0)

In [189]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [190]:
string_data = Series(['ssddd','DDSDd','avocado',np.nan])

In [191]:
string_data

0      ssddd
1      DDSDd
2    avocado
3        NaN
dtype: object

In [192]:
string_data.isnull()

0    False
1    False
2    False
3     True
dtype: bool

In [194]:
from numpy import nan as NA

In [195]:
data = Series([1,NA,3.5,NA,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [196]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [197]:
data = DataFrame([[1., 6.5, 3.], [1., NA, NA],
                  [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()

In [198]:
data
cleaned

0    1    2
0  1.0  6.5  3.0

In [199]:
data[4] = NA

In [200]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [201]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [202]:
df = DataFrame(np.random.randn(7, 3))
df.ix[:4,1]=NA; df.ix[:2,2] =NA

In [203]:
df

0         1         2
0 -0.415313       NaN       NaN
1 -0.774717       NaN       NaN
2  0.030566       NaN       NaN
3  1.318380       NaN -0.871343
4 -2.271320       NaN -0.069615
5 -0.256504 -1.179519 -0.680778
6 -0.163326 -0.376128  0.885669

In [204]:
df.dropna(thresh=3)

0         1         2
5 -0.256504 -1.179519 -0.680778
6 -0.163326 -0.376128  0.885669

In [205]:
df.fillna(0)

0         1         2
0 -0.415313  0.000000  0.000000
1 -0.774717  0.000000  0.000000
2  0.030566  0.000000  0.000000
3  1.318380  0.000000 -0.871343
4 -2.271320  0.000000 -0.069615
5 -0.256504 -1.179519 -0.680778
6 -0.163326 -0.376128  0.885669

In [208]:
df.fillna({1:0.5,2:-1})

0         1         2
0 -0.415313  0.500000 -1.000000
1 -0.774717  0.500000 -1.000000
2  0.030566  0.500000 -1.000000
3  1.318380  0.500000 -0.871343
4 -2.271320  0.500000 -0.069615
5 -0.256504 -1.179519 -0.680778
6 -0.163326 -0.376128  0.885669

In [209]:
_= df.fillna(0,inplace=True)

In [210]:
df

0         1         2
0 -0.415313  0.000000  0.000000
1 -0.774717  0.000000  0.000000
2  0.030566  0.000000  0.000000
3  1.318380  0.000000 -0.871343
4 -2.271320  0.000000 -0.069615
5 -0.256504 -1.179519 -0.680778
6 -0.163326 -0.376128  0.885669

In [211]:
df = DataFrame(np.random.randn(6,3))

In [212]:
df

0         1         2
0  0.081453  0.591830  0.515764
1  0.567630 -0.373311  0.097660
2 -1.899229 -1.713774 -1.699124
3 -1.132512 -0.858501 -0.760683
4 -0.939275 -1.298439 -0.766928
5  0.668827  0.699864  0.054225

In [213]:
data.fillna(data.mean())

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  6.5  3.0 NaN
2  1.0  6.5  3.0 NaN
3  1.0  6.5  3.0 NaN

In [214]:
data = Series(np.random.randn(10),index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
                     [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])

In [215]:
data

a  1   -0.484976
   2    0.231256
   3    1.145362
b  1    0.227230
   2   -0.836547
   3   -1.949311
c  1   -1.169784
   2   -0.750587
d  2    0.723306
   3    0.259526
dtype: float64

In [216]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [217]:
data['b']

1    0.227230
2   -0.836547
3   -1.949311
dtype: float64

In [218]:
data[:,2]

a    0.231256
b   -0.836547
c   -0.750587
d    0.723306
dtype: float64

In [219]:
data.unstack()

1         2         3
a -0.484976  0.231256  1.145362
b  0.227230 -0.836547 -1.949311
c -1.169784 -0.750587       NaN
d       NaN  0.723306  0.259526

In [220]:
data.unstack().stack()

a  1   -0.484976
   2    0.231256
   3    1.145362
b  1    0.227230
   2   -0.836547
   3   -1.949311
c  1   -1.169784
   2   -0.750587
d  2    0.723306
   3    0.259526
dtype: float64

In [221]:
frame = DataFrame(np.arange(12).reshape((4, 3)),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=[['Ohio', 'Ohio', 'Colorado'],
                           ['Green', 'Red', 'Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [222]:
frame.index.names

FrozenList([None, None])

In [223]:
frame.columns.names = ['state','color']

In [224]:
frame

state  Ohio     Colorado
color Green Red    Green
a 1       0   1        2
  2       3   4        5
b 1       6   7        8
  2       9  10       11

In [226]:
frame['Ohio']

color  Green  Red
a 1        0    1
  2        3    4
b 1        6    7
  2        9   10

In [228]:
frame.swaplevel('key1', 'key2')

KeyError: 'Level key1 not found'

In [229]:
frame.sortlevel(1)

state  Ohio     Colorado
color Green Red    Green
a 1       0   1        2
b 1       6   7        8
a 2       3   4        5
b 2       9  10       11

In [230]:
frame.swaplevel(0,1).sortlevel(0)

state  Ohio     Colorado
color Green Red    Green
1 a       0   1        2
  b       6   7        8
2 a       3   4        5
  b       9  10       11

In [231]:
frame.sum(level='key2')

AssertionError: Level key2 not in index

In [232]:
frame.sum(level='color',axis=1)

color  Green  Red
a 1        2    1
  2        8    4
b 1       14    7
  2       20   10

In [233]:
frame = DataFrame({'a': range(7), 'b': range(7, 0, -1),
                   'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
                   'd': [0, 1, 2, 0, 1, 2, 3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [234]:
frame2 = frame.set_index(['c','d'])

In [235]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [237]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [239]:
ser =Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [240]:
ser[1]

1.0

In [241]:
ser2 = Series(np.arange(3.),index=['a','b','c'])

In [ ]:
ser2