from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

In [2]:
arr = np.arange(10)

In [4]:
np.save('some_array.npy',arr)

In [5]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.savez('array_archive.npz', a=arr, b=arr)

In [7]:
arch = np.load('array_archive.npz')

In [8]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
!cat  array_ex.txt

cat: array_ex.txt: No such file or directory


In [10]:
x  = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])

In [11]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [12]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [13]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [14]:
np.dot(x,np.ones(3))

array([  6.,  15.])

In [15]:
from numpy.linalg import inv,qr

In [16]:
X =randn(5,5)

In [17]:
mat = X.T.dot(X)

In [18]:
inv(mat)

array([[ 0.9331, -0.0657,  0.2939,  0.7116,  0.6357],
       [-0.0657,  0.2259, -0.0119,  0.0162, -0.1475],
       [ 0.2939, -0.0119,  0.4402,  0.3904,  0.2684],
       [ 0.7116,  0.0162,  0.3904,  0.745 ,  0.4205],
       [ 0.6357, -0.1475,  0.2684,  0.4205,  0.7285]])

In [19]:
mat.dot(inv(mat))

array([[ 1., -0., -0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [-0.,  0.,  1.,  0.,  0.],
       [ 0., -0.,  0.,  1.,  0.],
       [ 0., -0.,  0., -0.,  1.]])

In [20]:
q,r = qr(mat)

In [21]:
r

array([[-15.6246,  -1.1271,  -9.5478,  16.2365,   8.0108],
       [  0.    ,  -6.0911,  -0.3476,   2.0813,  -2.7395],
       [  0.    ,   0.    ,  -4.0104,   2.1978,   0.0759],
       [  0.    ,   0.    ,   0.    ,  -2.013 ,   1.9611],
       [  0.    ,   0.    ,   0.    ,   0.    ,   0.9108]])

In [22]:
q

array([[-0.6639,  0.0377,  0.4336, -0.1858,  0.579 ],
       [-0.0332, -0.9339,  0.0719, -0.3219, -0.1343],
       [-0.2936, -0.0036, -0.887 , -0.2595,  0.2445],
       [ 0.6   ,  0.1642,  0.1037, -0.675 ,  0.383 ],
       [ 0.3345, -0.3155, -0.0969,  0.5822,  0.6635]])

In [23]:
samples = np.random.normal(size=(4,4))

In [24]:
samples

array([[ 0.3111, -0.4281,  1.237 ,  0.6572],
       [ 0.7519,  1.0691, -0.7042, -1.0194],
       [ 0.4322,  0.1067, -0.0545, -0.3348],
       [-1.0264, -0.0328,  0.2341, -0.1354]])

In [25]:
from random import normalvariate

In [26]:
N =1000000

In [29]:
%timeit samples = [normalvariate(0, 1) for _ in xrange(N)]
%timeit np.random.normal(size=N)

NameError: name 'xrange' is not defined

In [31]:
import random 
position = 0
walk = [position]
steps=1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position += step 
    walk.append(position)

In [39]:
plt.show()

NameError: name 'plt' is not defined

In [37]:
nsteps = 1000
draws = np.random.randint(0,2, size =nsteps)
steps=np.where(draws > 0,1,-1)
walk = steps.cumsum()
walk

array([ -1,  -2,  -3,  -2,  -3,  -4,  -3,  -2,  -3,  -4,  -3,  -4,  -5,
        -6,  -5,  -6,  -7,  -8,  -9, -10,  -9, -10,  -9,  -8,  -7,  -8,
        -7,  -8,  -9,  -8,  -7,  -6,  -7,  -8,  -9, -10,  -9, -10, -11,
       -10,  -9,  -8,  -7,  -6,  -7,  -6,  -7,  -6,  -5,  -6,  -7,  -6,
        -7,  -6,  -7,  -6,  -7,  -8,  -7,  -8,  -7,  -8,  -7,  -6,  -7,
        -6,  -7,  -6,  -5,  -6,  -7,  -8,  -9,  -8,  -7,  -8,  -9, -10,
       -11, -10, -11, -10, -11, -10, -11, -10, -11, -10, -11, -12, -13,
       -14, -15, -14, -13, -14, -15, -16, -17, -18, -17, -16, -17, -18,
       -17, -16, -15, -16, -15, -16, -17, -18, -17, -18, -17, -16, -15,
       -14, -15, -14, -13, -12, -11, -12, -11, -12, -11, -12, -11, -10,
        -9, -10,  -9,  -8,  -7,  -6,  -7,  -8,  -7,  -8,  -7,  -8,  -7,
        -8,  -9,  -8,  -9, -10, -11, -12, -13, -12, -13, -14, -13, -14,
       -13, -12, -13, -12, -11, -10, -11, -12, -13, -14, -13, -12, -11,
       -12, -11, -10,  -9,  -8,  -7,  -6,  -7,  -6,  -5,  -4,  -

In [34]:
walk.min()

-28

In [35]:
walk.max()

6

In [36]:
(np.abs(walk)).argmax()

105

In [46]:
nwalks = 5000
nsteps =1000
draws = np.random.randint(0,2, size=(nwalks,nsteps))
steps = np.where(draws > 0,1,-1)
walks = steps.cumsum(1)

In [47]:
walks.max()

117

In [48]:
walks.min()

-134

In [49]:
hits30 = (np.abs(walks) >= 30).any(1)

In [50]:
hits30.sum()

3439